[build]
  base = "/"
  command = "npm run build:prod"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/index.html"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
