[build]
    base = "/"
    command = "npm run build:prod"
    publish = "dist/"
[[redirects]]
    from = "/api/*"
    to = "http://ec2-44-209-30-178.compute-1.amazonaws.com:8080"
    status = 200
    headers = { Access-Control-Allow-Origin = "*" }
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"    